### ISSUE TITLE
Priest Mind Control + Mind Control AI

### ISSUE THREAD

**Issue by abhorhybrid** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4237]
Having issues using Mind Control:

After the cast bar fills one of two things occur:

1.  The Humanoid Mob  has "Immune" float over his head

2.  I am not in control of the mob and or player while I receive a buff saying my attack speed is slowed by 25 % for 60 seconds which I cannot right click disengage it.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
**Fix confirmed on PTR**

**Comment by Salce** [comment]
**This went live with Patch 11.0**

**Comment by Nzzoth** [comment]
2. I am not in control of the mob and or player while I receive a buff saying my attack speed is slowed by 25 % for 60 seconds which I cannot right click disengage it.

Still happens if you mindcontrol a already mindcontrolled humanoid.
